### ISSUE TITLE
some questions in ann

### ISSUE THREAD

**Issue by code4happylife** [kuhess/pso-ann#1]
hi,I am Senior in a university of china and I am stduying about pso-ann model for wifi-location indoor. 
I hava read your code and the output of the digital-data is a single number, the output-layer just one node. however in my research,the ann out put should be a coordinate（x,y）,means two output，so could u please show me how to modify the model to meet the output. thanks a lot. 
my email : 630393606@qq.com

**Comment by kuhess** [comment]
Sorry, I didn't see your message. The codebase has changed since 2016, you can find some examples in [examples](/kuhess/pso-ann/tree/main/examples) and [tests](/kuhess/pso-ann/tree/main/tests).
