### ISSUE TITLE
How to interpret the weigths

### ISSUE THREAD

**Issue by nkeito** [kuhess/pso-ann#2]
Once you have optimized the weights for ann, how can I interpret the acquired weigths so I can get the connections between nodes?

**Comment by kuhess** [comment]
Sorry, I didn't see you question before. FYI you can find a new class `MultiLayerPerceptronWeights` in the file [psoann/ann.py](/kuhess/pso-ann/tree/main/psoann/ann.py). There are the methods `from_particle_position` and `to_particle_position` which make transformations between the weights of ANN and the position vectors of particles.
