### ISSUE TITLE
BUG example_mnist.py

### ISSUE THREAD

**Issue by Jonasvdham** [kuhess/pso-ann#3]
Hi I believe there is a bug in 'example_mnist.py' in the function
`vector_to_weights`.
The indexing variable `idx` should be updated after the first iteration s.t.
`idx = idx_max`

Otherwise not the whole vector of weights is read.

**Comment by kuhess** [comment]
Thanks! I fixed it in https://github.com/kuhess/pso-ann/commit/e774897b4b5ebd7f23981f375363d63f83240513
